;Prueba de FCL

DATA:
    $MI-VAR IS NUMBER ;WITH 2 DECIMALS
    $I IS NUMBER
    $STRBUFFER IS TEXT 255
    $MODULO IS NUMBER
    
PROCEDURE:
    DISPLAY "VAMOS A HACER UN DISAN COUNT. INGRESE UN NÚMERO"
    ACCEPT $MI-VAR
    JOIN "VAMOS A HACER UN DISAN COUNT DESDE " AND $MI-VAR INTO $STRBUFFER
    DISPLAY $STRBUFFER
    WHILE $MI-VAR IS POSITIVE DO
        STORE $MI-VAR MODULO 2 INTO $MODULO
        IF $MODULO IS POSITIVE THEN
            JOIN $MI-VAR AND " ES PAR!" INTO $STRBUFFER
            DISPLAY $STRBUFFER
        END-IF
        STORE $MI-VAR MINUS 1 INTO $MI-VAR
    REPEAT
    DISPLAY "LISTO!"
    END
