;Demo de cobolartu, por lartu (?

DATA:
$NOMBRE IS TEXT 50		;Nombre del jugador
$OTRONOMBRE IS TEXT 50
$EDAD IS NUMBER
$NUM IS NUMBER
$REM IS NUMBER
$DECIMAL IS NUMBER WITH 2 DECIMALS ;Falta implementar decimales

PROCEDURE:
STORE "Hola, soy \YELLOWlartu\NORMAL. Tengo \RED" IN $NOMBRE
STORE $NOMBRE IN $OTRONOMBRE
DISPLAY $OTRONOMBRE
STORE 13 IN $EDAD
ADD 50 AND $EDAD IN $EDAD
SUBTRACT 40 FROM $EDAD IN $EDAD
DISPLAY $EDAD
DISPLAY "\NORMAL años.\n"
DISPLAY "Voy a \CYANmultiplicar\NORMAL algo...\n"
MULTIPLY 50 BY 50 IN $NUM
DISPLAY "50 x 50 da... \BLUE"
DISPLAY $NUM
DISPLAY "\NORMAL\n"
MULTIPLY 12345 BY 123456 IN $NUM
DISPLAY "12345 x 123456 da... \BLUE"
DISPLAY $NUM
DISPLAY "\NORMAL\n"
DISPLAY "Voy a \PINKDIVIDIR\NORMAL algo...\n"
DIVIDE 984621 BY 123 IN $NUM
DISPLAY "984621 / 123 da... \BLUE"
DISPLAY $NUM
DISPLAY "\NORMAL\n"
DIVIDE 416 BY 419 IN $NUM REMAINDER IN $REM
DISPLAY "416 / 419 da... \BLUE"
DISPLAY $NUM
DISPLAY "\NORMAL y sobra "
DISPLAY $REM
DISPLAY "\n"
DIVIDE 7 BY 2 IN _ REMAINDER IN $NUM
DISPLAY "7 módulo 2 da... \BLUE"
DISPLAY $NUM
DISPLAY "\NORMAL\n"
STORE 0 IN $NUM
WHILE $NUM IS LESS THAN 1000 DO
    DISPLAY "VAMOS A LOOPEAR "
    DISPLAY $NUM
    ADD 1 AND $NUM IN $NUM
    DISPLAY "\n"
REPEAT
STORE 30 IN $NUM
IF $NUM IS LESS THAN 50 THEN
    DISPLAY "Es menor a 50!\n"
ELSE
    DISPLAY "Es mayor a 50!\n"
END-IF
END
